---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: nginx:alpine
          volumeMounts:
            - name: {{ .Values.storage.name }}
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
      volumes:
        - name: {{ .Values.storage.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.storage.name }}

