---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.app.port }}
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ .Values.app.name }}